# Generated by Django 4.2.16 on 2024-09-05 20:57

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Roleplay',
                'verbose_name_plural': 'Roleplays',
            },
        ),
    ]
